### ISSUE TITLE
Suddenly broken with latest libseccomp

### ISSUE THREAD

**Issue by BachoSeven** [stoeckmann/xwallpaper#23] opened 2020-07-22 00:27 UTC
Hi, after updating libseccomp to the latest version (2.5.0-1) on Arch Linux, I get the following error when using xwallpaper:
```
xwallpaper: failed to set up stage 2 seccomp: Device or resource busy
```

I have not made any other significant modifications to my system which would explain the error, that's why I suspect libseccomp must be the issue here.

**Comment by stoeckmann** [comment] 2020-07-23 17:57
Hi BachoSeven,

I can confirm this issue with libseccomp 2.5.0 on my system as well. It seems to be related to the addition of USER_NOTIF. Makes me wonder if xwallpaper is one of the few applications out there which actually reduce their seccomp rules during runtime ...

**Comment by BachoSeven** [comment] 2020-08-04 22:21
Btw, most Arch users will not be affected by the big yet, as the package is still in the `testing` repos which I had active.

**Comment by IvarWithoutBones** [comment] 2020-09-07 14:31
This issue effects NixOS as well, the application is currently not usable.

**Comment by stoeckmann** [comment] 2020-09-07 17:19
@IvarWithoutBones 

Watch out, disabling seccomp this way definitely fixes the problems with xwallpaper, but please read: https://github.com/seccomp/libseccomp/issues/273#issuecomment-668458070

In summary, the seccomp issue also leads to systemd issues which are silently ignored. I would recommend to fix seccomp instead to have a greater impact on software used on NixOS beside xwallpaper.

**Comment by stoeckmann** [comment] 2020-12-26 09:09
This does not occur with libseccomp 2.5.1 anymore, which has been released for a while. Therefore I will close this ticket.
Thanks again @BachoSeven for pointing this out.

@IvarWithoutBones you have removed the seccomp support in NixOS. They updated to 2.5.1 as well. Can you please create a new pull request which reverts the seccomp-removal from xwallpaper?

**Closed by stoeckmann** 2020-12-26 09:09 UTC

**Comment by IvarWithoutBones** [comment] 2020-12-26 20:24
> @IvarWithoutBones you have removed the seccomp support in NixOS. They updated to 2.5.1 as well. Can you please create a new pull request which reverts the seccomp-removal from xwallpaper?

Thank you for the ping! I've just PR'd that.
