### ISSUE TITLE
xwallpaper: failed to parse 1600px-Sunflower_from_Silesia2.jpg

### ISSUE THREAD

**Issue by thomas10-10** [stoeckmann/xwallpaper#22] opened 2020-06-02 17:23 UTC
Hi, 
I can't get Xwallpaper to work. I have the following error:
 xwallpaper: failed to parse 1600px-Sunflower_from_Silesia2.jpg
What does this error message mean? 
The image works with feh.

Thank you

Image link: https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Sunflower_from_Silesia2.jpg/1600px-Sunflower_from_Silesia2.jpg

**Comment by stoeckmann** [comment] 2020-06-03 17:21
Thank you for your report and supplying an input file so I can test it directly.

First off: Is this a problem with this specific file or with JPG files in general, i.e. is your xwallpaper instance compiled with jpeg support?

It is weird, because I have no issue using it (exact call was: xwallpaper --zoom Sunflower_from_Silesia2.jpg).

So there must be a difference between my setup and yours. What I would like to know is:
- your system architecture (uname -m)
- your libjpeg library in use and its version (depends on your distribution how to look up)
- linker information about xwallpaper (ldd $(which xwallpaper))
- output of xwallpaper in debug mode (xwallpaper --debug --zoom Sunflower_from_Silesia2.jpg)

I have tested on amd64 with libjpeg-turbo 2.0.4.

A wild guess is that your libjpeg implementation is not libjpeg-turbo and that I unfortunately use a feature which your library does not have. But then again I wonder why you or distributors of the binary have been able to compile xwallpaper.

**Comment by kadadot216** [comment] 2020-07-03 12:21
Hello, I have encountered the same issue as described.

Have compiled a first time, but it did not warn me about the missing `libjpeg-turbo` library.
Installed it from dnf, then recompiled a second time and it works this time!

If it didn't warned me about the missing `libjpeg-turbo`, it is because it has linked the program against the legacy `libjpeg` one?

Anyway thank you for this piece of software! :)

**Comment by stoeckmann** [comment] 2020-07-04 11:12
Hi kadadot216,

it is perfectly fine for xwallpaper if libjpeg/libjpeg-turbo is missing, because JPEG support is optional. Same is true for PNG and XPM. The rational behind this is that not every system has support for these types, although such a system is probably quite rare.

In my case it's a default OpenBSD installation which has only libXPM. I can use that system for basic development purposes which do not require a browser (otherwise their dependencies would pull in JPEG and PNG anyway).

I'll close this issue since you and I have only reproduced it due to missing JPEG support. Also it's a month since thomas-10-10 opened this issue and did not reply again.

Thank you too for adding a comment to this issue.

**Closed by stoeckmann** 2020-07-04 11:12 UTC

**Comment by stoeckmann** [comment] 2022-09-05 16:38
Have you compiled xwallpaper by source? The solution was to install `libjpeg-turbo` package before compiling.

If you have installed the `xwallpaper` package itself, then please run `ldd xwallpaper`, use the `--debug` option, and post the output.

**Comment by mathstylish** [comment] 2022-09-05 16:42
> Have you compiled xwallpaper by source? The solution was to install `libjpeg-turbo` package before compiling.
> 
> If you have installed the `xwallpaper` package itself, then please run `ldd xwallpaper` and post the output, and use the `--debug` option and post the output.

Fortunately (or unfortunately) I already installed it from the source code, I installed the dependencies before installation. In the arch repositories I looked at the dependencies for that specific package and also installed it, but the same error.

PS: feh didn't work either, with a different error of course

**Comment by stoeckmann** [comment] 2022-09-05 17:17
If feh fails as well: Can you run `file wallpaper01.jpg` to see if it is really a JPEG file? Can you view the image in a browser or another tool? Maybe it's a JPEG format which is not supported... In that case, it would be great if you could send me the file per mail to tobias@stoeckmann.org so I can test it on my own.

**Comment by mathstylish** [comment] 2022-09-05 17:22
> If feh fails as well: Can you run `file wallpaper01.jpg` to see if it is really a JPEG file? Can you view the image in a browser or another tool? Maybe it's a JPEG format which is not supported... In that case, it would be great if you could send me the file per mail to [tobias@stoeckmann.org](mailto:tobias@stoeckmann.org) so I can test it on my own.

Yes, the error is not with xwallpaper or feh. I tested sxiv and the file and they all gave an error. Apparently the error is only with the jpeg format because png worked normally. Thanks for the help, I'll try to solve it.
