### ISSUE TITLE
failed to set up stage 2 seccomp: Resource busy (void)

### ISSUE THREAD

**Issue by zackarycw** [stoeckmann/xwallpaper#24] opened 2020-07-24 02:27 UTC
Running
`$ xwallpaper --zoom .config/wall.png`
results in
`xwallpaper: failed to set up stage 2 seccomp: Resource busy`

xwallpaper seemed to have worked fine for over a month adding that command to the $HOME/.xinitrc file. Running the daily
`# xbps-install -Su`
seems to have broken it? Searching on [google](https://www.google.com/search?source=hp&ei=ykYaX5HIL-uE9PwPlvqRkAo&q=xwallpaper%3A+failed+to+set+up+stage+2+seccomp%3A+Resource+busy&oq=xwallpaper%3A+failed+to+set+up+stage+2+seccomp%3A+Resource+busy&gs_lcp=CgZwc3ktYWIQAzIFCCEQqwJQ2UdY2Udg90hoAHAAeACAAXCIAXCSAQMwLjGYAQCgAQKgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwiR1c6V6-TqAhVrAp0JHRZ9BKIQ4dUDCAg&uact=5) tells me there are no great matches...

**Comment by stoeckmann** [comment] 2020-07-24 11:59
Hi @zackarycw,

the issue is a regression in libseccomp 2.5.0. It has been reported just a few days ago (https://github.com/stoeckmann/xwallpaper/issues/23). Considering that 2.5.0 has been released just a few days ago as well, I am not surprised that google was unable to index this message already. ;)

It looks like Void Linux already reverted back to 2.4.3, so this issue should be fixed for you very soon.

**Closed by stoeckmann** 2020-07-24 11:59 UTC
