### ISSUE TITLE
xwallpaper leaks/doesn't free xresources

### ISSUE THREAD

**Issue by stharward** [stoeckmann/xwallpaper#37] opened 2021-07-06 12:08 UTC
Some time between 0.6.6 and 0.7.0, xwallpaper started leaking X resources. Not really sure if that's the proper term for it, but it's whatever is tracked by the program `xrestop`. Anyway, I have a script that runs xwallpaper every 10 minutes, and over time, the number of connections increases with `<unknown>` PID identifiers. Eventually I can't start any more X programs because all X connections are in use. I've isolated the problem to xwallpaper. Version 0.6.6 did not leak resources, but 0.7.0 does.
I'll try to do additional debugging to see if I can isolate the merge where the regression was introduced.

**Comment by stharward** [comment] 2021-07-06 14:05
Follow up: I can reliably reproduce the problem with 0.7.1. Running `xwallpaper` and specifying an output that's disconnected leaks a resource every time. For example, running `xwallpaper --output HDMI-1 --zoom /path/to/image.jpg` results in `xwallpaper: output HDMI-1 was not found/disconnected, ignoring`, and a leaked X resource.

The bug was introduced in commit d0f52b1f0728a7b82e4f5b53444770d3246b6805. This commit can be cleanly reverted in current HEAD ( 421961892513eac3bbca4b997d21bd159752c9a8 ), which fixes the bug. Weirdly, running a bug-free version of the program somehow cleans up all the leaked X resources that had be hanging around from previous runnings of the program.

**Comment by stoeckmann** [comment] 2021-07-06 16:21
Hi @stharward, thanks for reporting this serious regression (due to the impact caused by a reasonable use case) and digging into it. I encountered the problem with daemon mode and mixture with hsetroot, feh, and nitrogen. I thought that I fixed interoperability but obviously this did not work.

My test case now consisted of mixing feh and xwallpaper calls -- with and without daemon mode and triggering xrandr messages endlessly. I was able to reproduce what you described and fixed this while keeping interoperability.

Please let me know if current master runs for your without issues. If it does, I will release a new version.

**Comment by stharward** [comment] 2021-07-08 02:11
> Please let me know if current master runs for your without issues. If it does, I will release a new version.

Yeah, looks good. Sometimes the background is gray (instead of image) when my monitors wake up, but at least now I don't get X resource exhaustion. Thanks!

**Comment by stharward** [comment] 2021-07-12 17:03
Follow up: I've had to revert this patch too. Somehow it's killing other X clients. It somehow gets itself into a state where the root window is gray, and then the next time it runs it sets the background, but kills another X client in the process. I've had it kill `xrestop` and my terminal. And it's still leaking X resources, just not as consistently.

**Comment by stoeckmann** [comment] 2021-07-13 16:17
Finally found time to get back to this topic. The gray background already looked like there is another issue waiting to show up. With your latest report I carefully reviewed the different code paths and concepts of X when it comes to atoms and the temporary or permanent retainment of resources.

With my latest commit your use case should be fixed (I have described it in the commit message so I will stumble upon it with a future git blame). It would be cool if you can test it. Also thanks again for your analysis and support in resolving this issue so far!

**Comment by stoeckmann** [comment] 2021-07-18 10:06
I have released xwallpaper 0.7.2 which contains the proposed fix. I don't know if it fully covers the subject but I don't want users of xwallpaper be exposed to the known leakage any longer.

Let me know if it works. My remark about `xwallpaper --daemon` has to be addressed anyway so I expect yet another release sooner than later anyway.

**Comment by stoeckmann** [comment] 2021-07-18 10:26
And I have just created a "spin-off" of this issue. As far as I understand your use case, you did not use `xwallpaper --daemon` and therefore we have two different operational modes which can leak resources.

So if the "one-shot mode" does not leak anymore, we can close this issue and keep track of the daemon subject separately.

**Comment by stoeckmann** [comment] 2021-08-08 12:44
Hi, I'm closing this ticket now. The --daemon aspect is solved now as well. If the problem shows up again, please let me know!

**Closed by stoeckmann** 2021-08-08 12:44 UTC
